version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: ezdxf
    versions:
    - 0.16.1
  - dependency-name: matplotlib
    versions:
    - 3.4.0
    - 3.4.1
  - dependency-name: llvmlite
    versions:
    - 0.36.0
  - dependency-name: numpy
    versions:
    - 1.20.0
